// Generated by CoffeeScript 1.3.1
(function() {
  var k;

  k = function(o) {};

  $(function() {
    $('.qqcontact').tooltip();
    return $('.no-opacity .cover img').bind('mouseover', function() {
      return $(this).css({
        'opacity': '0.5'
      });
    }).bind('mouseout', function() {
      return $(this).css({
        'opacity': '1'
      });
    });
  });

}).call(this);
