// Generated by CoffeeScript 1.3.1
(function() {
  var k;

  k = function(o) {
    return console.log(o);
  };

  $(function() {
    $('.qqcontact').tooltip();
    return k('hello world, welcome to dazake');
  });

}).call(this);
